### ISSUE TITLE
List of phrases

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#1]
## Value proposition

**As a** user
**I need** to see a list of phrases of my kid
**to be able to** keep them as a memory

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/156643713-b5ecbf9d-a633-4ba9-b900-5b6a05f43f77.png />

## Acceptance Criteria

- [x] The list should contain all phrases of user´s kid
- [x] Every phrase should be shown as a own card
- [x] Every phrase card should contain a date and a text

## Tasks

- [x] Project setup
- [x] Global Styles
- [x] components/PhraseCard
  - [x] Storybook
  - [x] Tests
  - [x] Styling
- [x] components/PhraseCardList
  - [x] Add PhraseCard
  - [x] Storybook
  - [x] Tests
  - [x] Styling
- [x] styled components
- [x] Check accessibility
- [x] Check on mobile
- [x] Add to app
