### ISSUE TITLE
Add an image

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#12]
## Value proposition

**As a** user
**I need** to add an image to my phrase card
**to be able to** link the phrase to a visual memory

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/158572131-b05056cd-d109-4be2-b621-2f60e7aa0694.png />

## Acceptance Criteria

- [x] On each card there should be an add icon 
- [x] The image should be saved as an avatar on each card
- [x] If no image is selected there should be a whitespace on each card

## Tasks

- [x] implement cloudinary
- [x] implement axios
- [ ] Add an upload component
- [x] Adjust phrase state 
- [x] Adjust phrase card component
- [x] Testing
