### ISSUE TITLE
Add modal message to form

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#14]
## Value proposition

**As a** user
**I need** to choose between staying on the adding page or get directed to the all phrases page
**to be able to** have more control of the ui.

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/158561949-bd855490-e957-4b0a-a341-63238cb2d4f3.png />

## Acceptance Criteria

- [ ] Onclick "hinzufügen" button the user should stay on the page
- [ ] Onclick "alle" button the user should directed to all phrases

## Tasks

- [ ] Add modal message to form component
- [ ] Delete settimeout from form component
- [ ] Add link to modal message
- [ ] Testing
- [ ] Check mobile
