### ISSUE TITLE
Read more button 

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#16]
## Value proposition

**As a** user
**I need** a read more button on each card
**to be able to** see all content of what my kid said

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/159152264-aa4ad918-e70a-4f09-ac9f-9e968c0b3ebe.png />

## Acceptance Criteria

- [ ] A read more button as an icon on each card if the text length is longer then 150 characters
- [ ] Each Card should have same height
- [ ] When a read more button is already open and a user clicks on another card on the read more button, the old one should collapse and the new one should be shown 

## Tasks

- [ ] Add a components/PhraseCardText
  - [ ] Add a toggle button
- [ ] Replace p tag to PhraseCardText in PhraseCard component
- [ ] Set a limit for characters
- [ ] State management
- [ ] Change styling of card component
- [ ] Tests
- [ ] Check mobile
