### ISSUE TITLE
Delete a photo

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#17]
## Value proposition

**As a** user
**I need** an additional delete button on each card
**to be able to** delete only the photo if I don´t like it

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/159152796-980c10c8-a85b-4377-9576-2fbfc43387aa.png />

## Acceptance Criteria

- [x] When a user hover over the image on desktop or when a user touch the image on mobile there should be an delete icon visible
- [x] Each photo can be deleted separately on delete icon click
- [ ] On clicking the photo delete button, just the image getting deleted. The phrase card is still visible

## Tasks

- [x] Add a component/PhraseCardImage
  - [x] Move react cloudinary from PhraseCard to PhraseCardImage component
  - [x] Add delete icon
- [x] Change handling when hover or touch on image
  - [x] Add new state 
- [x] Replace image in PhraseCard component with PhraseCardImage
- [x] Pass props through
- [ ] Tests
- [x] Styling
- [x] Check mobile
