### ISSUE TITLE
Loading info

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#18]
## Value proposition

**As a** user
**I need** a visible loading info when I upload a photo
**to be able to** check if my upload actually works 

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/159154674-b5bc7e90-bd7e-4216-806c-c2f439975c10.png />

## Acceptance Criteria

- [x] Loading bar should be visible after uploading a picture
- [x] Loading bar disappears when the photo is visible on the card

## Tasks

- [x] Add components/LoadingInfo
- [x] Add LoadingInfo to pages
- [x] Adjust upload function
- [x] Tests
- [x] Check mobile
