### ISSUE TITLE
Form and card refactoring

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#19]
## Value proposition

**As a** user
**I need** an additional input field to add my kids name and an optional photo upload field
**to be able to** enhance my phrasecard

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/159170823-159db023-7f14-43af-b815-c6d2e2033d65.png />

## Acceptance Criteria

- [x] Select field with created kids names should be in the form
- [x] An optional image upload should be in the form
- [x] When form is submitted then the name of the kid and the image should be visible on the card
- [x] If no image is selected then the space of the image should be free
- [x] If no kid is created then there should be a plus icon where the user gets directed to the create a kid page and after adding a kid the user gets redirected to the form field

## Tasks

- [x] Adjust PhraseForm component
- [x] Adjust PhraseCard component
- [x] Adjust state
- [x] Tests
- [x] Storybook
- [x] Check mobile
- [x] Accessibility check
