### ISSUE TITLE
Bookmark a phrase

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#2]
## Value proposition

**As a** user
**I need** to bookmark a phrase
**to be able to** save my favorite phrases

## Description

<img width="200" src=https://user-images.githubusercontent.com/97166533/156651072-014b9741-a97b-463f-8701-202841ec5291.png />

## Acceptance Criteria

- [x] Bookmark button should be visible on the top right of the card
- [x] Bookmark button should be toggleable
- [x] Color of the bookmark button should change

## Tasks

- [x] component/HeartIcon
  - [x] Add svg´s
  - [x] Tests
- [x] components/PhraseCard
  - [x] Add HeartIcon
  - [x] Place icon
  - [x] Storybook
  - [x] Tests
  - [x] Styling
- [x] components/PhraseCardList
- [x] Pass props through to bookmark button
- [x] Testing on mobile
- [x] Add to app
