### ISSUE TITLE
Create a kid

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#20]
## Value proposition

**As a** user 
**I need** a page where I can create a kid
**to be able to** use it afterwards in the form field and see the different phrases of my kids

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/159171659-b3c5b9d6-0e53-40f5-b03f-e63fc3bbad89.png />

## Acceptance Criteria

- [x] Add a kid icon should be visible in the header
- [x] A new simple form should be open to create a kid
- [x] Input fields should be required
- [x] Max length of 20 characters in name input
- [x] After creating a kid, the kid should be visible underneath the form and the user should be redirected to the "Hinzufügen" page

## Tasks

- [x] Add components/KidsForm
- [x] New page kidsForm
- [x] New state for kids in App component
- [x] Add components/KidsCard
- [x] Passing props through
- [x] Test
- [x] Storybook
- [x] Check Mobile
