### ISSUE TITLE
Card refactoring

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#24]
## Value proposition

**As a** user
**I need** a nicer phrase card
**to be able to** see all important information faster

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/160293526-eca177da-d456-4282-ab29-174af04c32ac.png />

## Acceptance Criteria

- [x] New phrasecard design
- [x] Picture on the left side
  - [x] If no picture was selected there should be an add image icon visible instead
- [x] All information on the right side
- [x] Buttons on the bottom

## Tasks

- [x] Adjust PhraseCard component
- [x] Adjust Styling
- [x] Check functionality
- [x] Check mobile
