### ISSUE TITLE
Flip a card

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#25]
## Value proposition

**As a** user
**I need** a flip option on each phrase card
**to be able to** so see the phrase and the information on one side of the card and a full width picture according to the phrase on the other side

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/160293869-aad5dd16-5fce-4dd7-8003-3cf4b0490c04.png />

## Acceptance Criteria

- [x] A flip button on each card
- [x] When clicking the button the card flips around
- [x] A full width picture on one side (same as on the other side)
- [x] If no picture is selected an add image icon is visible

## Tasks

- [x] Adjust PhraseCard component
- [x] Implement flip icon
- [x] Install ReactCardFlip
- [x] Adjust styling
- [x] Check Mobile
