### ISSUE TITLE
Filter list

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#31]
## Value proposition

**As a** user
**I need** a filterlist on "Alle" and "Favoriten" page
**to be able to** filter by kids name

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/160684192-00b82824-0d01-4cec-ac56-bcf78b54bf4a.png />

## Acceptance Criteria

- [x] Dynamic filterlist on "Alle" and "Favoriten" page sorted by name
- [x] "Alle" should be default 
- [x] On filterbutton click color should change
- [x] Just filtered cards should be shown

## Tasks

- [x] Add FilterList component
- [x] New state for filterbuttons in App.js 
- [x] Add FilterList to all phrases and favorite page
- [x] Tests
- [x] Storybook
- [x] Check Mobile
