### ISSUE TITLE
List of phrases

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#4]
## Value proposition

**As a** user
**I need** to see a list of phrases of my kid
**to be able to** keep them as a memory

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/156643713-b5ecbf9d-a633-4ba9-b900-5b6a05f43f77.png />

## Acceptance Criteria

- [ ] The list should contain all phrases of user´s kid
- [ ] Every phrase should be shown as a own card
- [ ] Every phrase card should contain a date and a text

## Tasks

- [ ] Project setup
- [ ] Global Styles
- [ ] components/PhraseCard
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
- [ ] styled components
- [ ] Check accessibility
- [ ] Check on mobile
- [ ] Add to app
