### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#5]
## Value proposition

**As a** user
**I need** a separate page for my favorite phrases
**to be able to** to find them with less effort.

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/157655252-0b826cfd-594d-47f0-b86b-0ba858f46690.png>

## Acceptance Criteria

- [x] Navigation should be visible at the bottom and be fixed
- [x] Navigation should show which phrases ("Alle" or "Favouriten") is currently looking at
- [x] Error message should be visible if no phrases are bookmarked

## Tasks

- [x] components/Navigation
  - [x] Storybook
  - [x] Tests
- [x] Add React Router
- [x] Add Pages
- [x] Check Mobile
