### ISSUE TITLE
Bookmark a phrase

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#5]
## Value proposition

**As a** user
**I need** to bookmark a phrase
**to be able to** save my favourite phrases

## Description

<img width="200" src=https://user-images.githubusercontent.com/97166533/156651072-014b9741-a97b-463f-8701-202841ec5291.png />

## Acceptance Criteria

- [ ] Bookmark button should be visible on the top right of the card
- [ ] Bookmark button should be toggleable

## Tasks

- [ ] components/PhraseCard
  - [ ] Add button (heart icon)
  - [ ] Place icon
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
- [ ] Create useToggle hook
- [ ] components/App 
  - [ ] Import useToggle
- [ ] PropTypes
- [ ] Testing on mobile
- [ ] Add to app
