### ISSUE TITLE
Buttons to filter phrases

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#6]
## Value proposition

**As a** user
**I need** buttons
**to be able to** switch between all phrases and my favourite bookmarked ones

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/156738663-9cc1bf48-cd6b-409a-a2f2-be46d0842a8c.png />

## Acceptance Criteria

- [ ] Own Section with 2 buttons on top of phrases list
- [ ] One button for all phrases
- [ ] One button for favorite phrases
- [ ] Buttons should be toggleable
- [ ] Active button should change color

## Tasks

- [ ] component/Button
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
- [ ] component/PhraseFilter
  - [ ] Storybook
  - [ ] Tests
  - [ ] Add filter buttons
  - [ ] Styling
- [ ] component/PhraseCardlist
  - [ ] Add PhraseFilter
  - [ ] Eventhandler function(s)
  - [ ] useState
- [ ] Pass props through components
- [ ] PropTypes
- [ ] Check UI on mobile
