### ISSUE TITLE
Filter phrases

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#7]
## Value proposition

**As a** user
**I need** to filter my phrases
**to be able to** see just my favorite phrases 

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/156749856-25da9a3e-c8fb-42df-9ae6-4263d623b56f.png />

<img width="200" src=https://user-images.githubusercontent.com/97166533/156753091-cb9bfe4c-78ba-4e27-8c44-75f62874dc8c.png />

## Acceptance Criteria

- [ ] All phrases should be shown as default
- [ ] All phrases should be shown when "Alle" button is clicked
- [ ] Just bookmarked phrases should be shown when "Favoriten" button is clicked
- [ ] When no phrases are bookmarked and "Favoriten" button is clicked a message should be displayed underneath the PhraseFilter section
- [ ] Filter buttons should still work even the message is displayed 

## Tasks

- [ ] components/ErrorMessage
  - [ ] Storybook
  - [ ] Tests
  - [ ] Styling
- [ ] components/PhraseCardsList
  - [ ] Add ErrorMessage
  - [ ]
