### ISSUE TITLE
Add a phrase

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#7]
## Value proposition

**As a** user
**I need** to add phrases of my kid
**to be able to** save them for later.

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/157863027-faa4a941-6db2-409b-bd54-79dedd68f964.png />

## Acceptance Criteria

- [x] User can enter a date and a phrasetext
- [x] Date and phrasetext should be required
- [ ] After adding a phrase the user should directed to the "Alle" Page and see the created phrase on top 
- [x] Navigation should show three navlinks
- [x] "Hinzufügen" page should be the first visible page when a user opens the app

## Tasks

- [x] components/PhraseForm
- [x] components/Navigation
  - [x] Add new navlink
- [x] components/App
  - [x] Add route
- [x] Check on Mobile
- [x] Tests
- [x] Styling
