### ISSUE TITLE
Delete a phrase

### ISSUE THREAD

**Issue by MichiBerger** [MichiBerger/capstone-project#8]
## Value proposition

**As a** user
**I need** to delete a phrase
**to be able to** keep a better overview of my phrases

## Description
<img width="200" src=https://user-images.githubusercontent.com/97166533/158019511-780e163e-de7d-40f4-a008-530b780a769b.png />
<img width="200" src=https://user-images.githubusercontent.com/97166533/158020084-352b435b-4e41-4863-a6f3-ee08229cc2dd.png />

## Acceptance Criteria

- [x] There should be a delete button visible on the top right of each card
- [x] When the user clicks the delete button a modal message should be shown
  - [x] If the user clicks yes, the modal message disappears, the phrase will be deleted and the user sees the other phrases again 
  - [x] If the user clicks no, the modal message disappears and the user will see the other phrases again
- [x] Delete button is visibile on each card in "Alle" and "Favoriten" page

## Tasks

- [x] components/DeleteButton
- [x] Add DeleteButton to components/PhraseCard
- [x] components/ModalMessage
- [x] Add ModalMessage to components/PhraseCard
- [x] Tests
- [ ] Mobile testing
